services:
  jupyter:
    image: quay.io/jupyter/scipy-notebook:2026-07-28
    restart: unless-stopped

    ports:
      - "127.0.0.1:8888:8888"

    volumes:
      - ${JUPYTER_WORK_DIR:-./notebooks}:/home/jovyan/work
      - ./jupyter/custom/custom.css:/home/jovyan/.jupyter/custom/custom.css:ro
      - ./static/img/echorepo_logo_light.svg:/home/jovyan/.jupyter/custom/echorepo_logo.svg:ro

    environment:
      JUPYTER_TOKEN: ${JUPYTER_TOKEN}
      ECHOREPO_URL: "http://echorepo-lite:8000"
      PYTHONPATH: "/home/jovyan/work"

    command:
      - start-notebook.py
      - --ServerApp.root_dir=/home/jovyan/work
      - --custom-css

    networks:
      - echorepo-shared

networks:
  echorepo-shared:
    external: true
