name: i18n auto-translate

on:
  workflow_dispatch:
  push:
    paths:
      - "echorepo/templates/**.html"
      - "echorepo/**.py"
      - "messages.pot"

jobs:
  translate:
    runs-on: ubuntu-latest

    services:
      libretranslate:
        image: libretranslate/libretranslate:latest
        ports:
          - 5000:5000
        env:
          LT_LOAD_ONLY: en,cs,nl,fi,fr,de,el,it,pl,pt,ro,sk,es
          LT_DISABLE_WEB_UI: true
          LT_API_KEYS: "false"
        options: >-
          --health-cmd="wget -qO- http://localhost:5000/languages || exit 1"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=20

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install babel polib requests

      - name: Ensure babel.cfg & extract messages
        run: |
          # Use your existing babel.cfg if you have one; otherwise create a basic one:
          if [ ! -f babel.cfg ]; then
            cat > babel.cfg <<'CFG'
          [python: **.py]

          [jinja2: echorepo/templates/**.html]
          extensions=jinja2.ext.autoescape,jinja2.ext.with_
          CFG
          fi
          pybabel extract -F babel.cfg -k _ -o messages.pot .

      - name: Auto-translate & compile
        env:
          LT_ENDPOINT: http://localhost:5000
        run: |
          python tools/auto_translate.py \
            --pot messages.pot \
            --trans-dir echorepo/translations \
            --endpoint "${LT_ENDPOINT}"

      - name: Create PR with updated translations
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "i18n: auto-translate updated strings"
          title: "i18n: auto-translate updated strings"
          branch: i18n/auto
          body: |
            This PR was generated automatically:
            - Extracted latest strings
            - Updated/created PO files
            - Auto-translated missing entries via LibreTranslate
            - Compiled MO files

            Please review wording for key pages.
